version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  HelloPHP:
    image: php:5.6-apache
    environment:
      FAVORITE_COLOR: ${favorite_color}
    stdin_open: true
    volumes:
    - ${php_template_dir}:/var/www/html:ro
    tty: true
    links:
    - mysql:mysql-test
    ports:
    - ${lb_port}:80/tcp
    labels:
      io.rancher.container.pull_image: always
